### ISSUE TITLE
GLFW.glfwInit() and -XstartOnFirstThread

### ISSUE THREAD

**Issue by Protoxy22** [fabmax/kool#10]
Hello, I wanted to make a new test on my macbook arm64.
I built PhysX with jni natives and it went good.

But I can't run the demo, even with the argument/VM option "-XstartOnFirstThread" on Intellij, it crash at start:

I really carefully check if the VM options was valid, and it if it is interpreted at the launch.
`Executing task ' run -XstartOnFirstThread'`

It is really strange, does it launch for you on a macos ? 

```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.lwjgl.glfw.GLFW.glfwInit(GLFW.java:1046)
	at de.fabmax.kool.DesktopImpl.<clinit>(JvmPlatform.kt:62)
	at de.fabmax.kool.JvmPlatformKt.createContext(JvmPlatform.kt:28)
	at de.fabmax.kool.demo.MainKt.main(Main.kt:18)
	at de.fabmax.kool.demo.MainKt.main(Main.kt)
Caused by: java.lang.IllegalStateException: GLFW may only be used on the main thread and that thread must be the first thread in the process. Please run the JVM with -XstartOnFirstThread. This check may be disabled with Configuration.GLFW_CHECK_THREAD0.
	at org.lwjgl.glfw.EventLoop.<clinit>(EventLoop.java:30)
	... 5 more
Caused by: java.lang.IllegalStateException: GLFW may only be used on the main thread and that thread must be the first thread in the process. Please run the JVM with -XstartOnFirstThread. This check may be disabled with Configuration.GLFW_CHECK_THREAD0.

```

Thank you in advance, I really liked the demo update of the island =)

EDIT: SOLVED
I added `jvmArgs("-XstartOnFirstThread")` in the gradle run task

**Comment by Protoxy22** [comment]
I solved it:
I added jvmArgs("-XstartOnFirstThread") in the gradle run task

**Comment by fabmax** [comment]
Hmm still a bit odd that this only occurs on arm64 / macos. But good to know there's an easy fix.
