### ISSUE TITLE
NoSuchElementException when adding Ui2 Node to the scene

### ISSUE THREAD

**Issue by Protoxy22** [fabmax/kool#32]
Hi,
I would like to make a scene editor with a lists of models objects on the scene, and gizmo when selecting a model.

But when I try to render a simple panel on my 3D scene I'm having NoSuchElementException
Do you know a simple method to render an ui window in top of a 3D scene ?

**Code:**
```
    override fun Scene.setupMainScene(ctx: KoolContext) {
        camera.clipFar = 10000f
        defaultCamTransform()

        setupUiScene(clearScreen = false)

        +Panel(colors = Colors.singleColorLight(MdColor.LIGHT_GREEN)) {
            modifier
                .size(400.dp, 300.dp)
                .align(AlignmentX.Center, AlignmentY.Center)
                .background(RoundRectBackground(colors.background, 16.dp))

            val clickCount = weakRememberState(0)
            Button("Click me!") {
                modifier
                    .alignX(AlignmentX.Center)
                    .margin(sizes.largeGap * 4f)
                    .padding(horizontal = sizes.largeGap, vertical = sizes.gap)
                    .font(sizes.largeText)
                    .onClick { clickCount.set(clickCount.value + 1) }
            }
            Text("Button clicked ${clickCount.use()} times") {
                modifier
                    .alignX(AlignmentX.Center)
            }
        }
    }
```

**Error:**
```
Exception in thread "main" java.util.NoSuchElementException: Mesh does not include required vertex attribute: attrib_positions
	at de.fabmax.kool.modules.ksl.KslShader.setupAttributes(KslShader.kt:182)
	at de.fabmax.kool.modules.ksl.KslShader.onPipelineSetup(KslShader.kt:28)
	at de.fabmax.kool.pipeline.Shader.createPipeline(Shader.kt:14)
	at de.fabmax.kool.pipeline.DepthMapPass.getDepthPipeline(DepthMapPass.kt:40)
	at de.fabmax.kool.pipeline.DepthMapPass.setupDrawCommand(DepthMapPass.kt:31)
	at de.fabmax.kool.util.SimpleShadowMap.setupDrawCommand(ShadowMap.kt:73)
	at de.fabmax.kool.pipeline.DepthMapPass$1.invoke(DepthMapPass.kt:25)
	at de.fabmax.kool.pipeline.DepthMapPass$1.invoke(DepthMapPass.kt:22)
	at de.fabmax.kool.pipeline.RenderPass.afterCollectDrawCommands(RenderPass.kt:124)
	at de.fabmax.kool.pipeline.RenderPass.collectDrawCommands(RenderPass.kt:81)
	at de.fabmax.kool.scene.Scene.renderScene(Scene.kt:87)
	at de.fabmax.kool.KoolContext.render(KoolContext.kt:186)
	at de.fabmax.kool.platform.Lwjgl3Context.renderFrame$kool_core(Lwjgl3Context.kt:134)
	at de.fabmax.kool.platform.Lwjgl3Context.run(Lwjgl3Context.kt:108)
	at net.ravage.engine.scenes.RavageScene.<init>(RavageScene.kt:52)
	at net.ravage.engine.world.WorldCreator.<init>(WorldCreator.kt:10)
	at net.ravage.engine.RavageEngine.<init>(RavageEngine.kt:19)
	at net.ravage.engine.RavageApplicationKt.main(RavageApplication.kt:29)
	at net.ravage.engine.RavageApplicationKt.main(RavageApplication.kt)
```

**Comment by fabmax** [comment]
The error was caused by the ShadowMapPass not being able to create a depth shader for the UI meshes, because they don't have a traditional vertex position attribute. The error shouldn't occur anymore.

However, apparently you had a shadow map enabled for your UI scene, which does not really make sense for a UI scene and probably wastes a lot of performance

**Comment by Protoxy22** [comment]
The latest commit fixed the issue, thanks for the help
It was because of shadowmap yes
